var annotated_dup =
[
    [ "OSL_ALPHA_PARAMS", "struct_o_s_l___a_l_p_h_a___p_a_r_a_m_s.html", "struct_o_s_l___a_l_p_h_a___p_a_r_a_m_s" ],
    [ "osl_audio_channelinfo", "structosl__audio__channelinfo.html", "structosl__audio__channelinfo" ],
    [ "OSL_AUDIO_VOICE", "struct_o_s_l___a_u_d_i_o___v_o_i_c_e.html", "struct_o_s_l___a_u_d_i_o___v_o_i_c_e" ],
    [ "OSL_CONTROLLER", "struct_o_s_l___c_o_n_t_r_o_l_l_e_r.html", "struct_o_s_l___c_o_n_t_r_o_l_l_e_r" ],
    [ "OSL_FAST_VERTEX", "struct_o_s_l___f_a_s_t___v_e_r_t_e_x.html", "struct_o_s_l___f_a_s_t___v_e_r_t_e_x" ],
    [ "OSL_FAST_VERTEX_COLOR32", "struct_o_s_l___f_a_s_t___v_e_r_t_e_x___c_o_l_o_r32.html", "struct_o_s_l___f_a_s_t___v_e_r_t_e_x___c_o_l_o_r32" ],
    [ "OSL_FONT", "struct_o_s_l___f_o_n_t.html", "struct_o_s_l___f_o_n_t" ],
    [ "OSL_FONT_FORMAT_HEADER", "struct_o_s_l___f_o_n_t___f_o_r_m_a_t___h_e_a_d_e_r.html", "struct_o_s_l___f_o_n_t___f_o_r_m_a_t___h_e_a_d_e_r" ],
    [ "OSL_FONTINFO", "struct_o_s_l___f_o_n_t_i_n_f_o.html", "struct_o_s_l___f_o_n_t_i_n_f_o" ],
    [ "OSL_IMAGE", "struct_o_s_l___i_m_a_g_e.html", "struct_o_s_l___i_m_a_g_e" ],
    [ "OSL_KEYBOARD", "struct_o_s_l___k_e_y_b_o_a_r_d.html", "struct_o_s_l___k_e_y_b_o_a_r_d" ],
    [ "OSL_KEYLIST", "union_o_s_l___k_e_y_l_i_s_t.html", "union_o_s_l___k_e_y_l_i_s_t" ],
    [ "OSL_LINE_VERTEX", "struct_o_s_l___l_i_n_e___v_e_r_t_e_x.html", "struct_o_s_l___l_i_n_e___v_e_r_t_e_x" ],
    [ "OSL_LINE_VERTEX_COLOR32", "struct_o_s_l___l_i_n_e___v_e_r_t_e_x___c_o_l_o_r32.html", "struct_o_s_l___l_i_n_e___v_e_r_t_e_x___c_o_l_o_r32" ],
    [ "OSL_MAP", "struct_o_s_l___m_a_p.html", "struct_o_s_l___m_a_p" ],
    [ "OSL_MEMSTATUS", "struct_o_s_l___m_e_m_s_t_a_t_u_s.html", "struct_o_s_l___m_e_m_s_t_a_t_u_s" ],
    [ "OSL_PALETTE", "struct_o_s_l___p_a_l_e_t_t_e.html", "struct_o_s_l___p_a_l_e_t_t_e" ],
    [ "OSL_PRECISE_VERTEX", "struct_o_s_l___p_r_e_c_i_s_e___v_e_r_t_e_x.html", "struct_o_s_l___p_r_e_c_i_s_e___v_e_r_t_e_x" ],
    [ "OSL_REMOTECONTROLLER", "struct_o_s_l___r_e_m_o_t_e_c_o_n_t_r_o_l_l_e_r.html", "struct_o_s_l___r_e_m_o_t_e_c_o_n_t_r_o_l_l_e_r" ],
    [ "OSL_REMOTEKEYLIST", "union_o_s_l___r_e_m_o_t_e_k_e_y_l_i_s_t.html", "union_o_s_l___r_e_m_o_t_e_k_e_y_l_i_s_t" ],
    [ "OSL_SFLETTER", "struct_o_s_l___s_f_l_e_t_t_e_r.html", "struct_o_s_l___s_f_l_e_t_t_e_r" ],
    [ "OSL_SFONT", "struct_o_s_l___s_f_o_n_t.html", "struct_o_s_l___s_f_o_n_t" ],
    [ "OSL_SOUND", "struct_o_s_l___s_o_u_n_d.html", "struct_o_s_l___s_o_u_n_d" ],
    [ "OSL_UVFLOAT_VERTEX", "struct_o_s_l___u_v_f_l_o_a_t___v_e_r_t_e_x.html", "struct_o_s_l___u_v_f_l_o_a_t___v_e_r_t_e_x" ],
    [ "OSL_VIRTUALFILENAME", "struct_o_s_l___v_i_r_t_u_a_l_f_i_l_e_n_a_m_e.html", "struct_o_s_l___v_i_r_t_u_a_l_f_i_l_e_n_a_m_e" ],
    [ "oslNetConfig", "structosl_net_config.html", "structosl_net_config" ],
    [ "oslSaveLoad", "structosl_save_load.html", null ],
    [ "remotePsp", "structremote_psp.html", "structremote_psp" ],
    [ "VIRTUAL_FILE", "struct_v_i_r_t_u_a_l___f_i_l_e.html", "struct_v_i_r_t_u_a_l___f_i_l_e" ],
    [ "VIRTUAL_FILE_SOURCE", "struct_v_i_r_t_u_a_l___f_i_l_e___s_o_u_r_c_e.html", "struct_v_i_r_t_u_a_l___f_i_l_e___s_o_u_r_c_e" ]
];