cmake_minimum_required(VERSION 3.10)
project(OSLibSamples C)

add_subdirectory(adhoc)
add_subdirectory(audio)
add_subdirectory(dialog)
add_subdirectory(helloWorld)
add_subdirectory(internetBrowser)
add_subdirectory(intraFont)
add_subdirectory(map)
add_subdirectory(net)
add_subdirectory(OSK)
add_subdirectory(rectAndFonts)
add_subdirectory(saveAndLoad)
add_subdirectory(sfont)
add_subdirectory(shapes)
