/**
 * @file bgm.h
 * @brief BGM (Background Music) audio format and playback for OSLib.
 *
 * BGM is OSLib's native audio format using IMA-ADPCM compression for efficient
 * audio playback on PSP. It supports both RAM-based and streaming playback modes.
 *
 * @section bgm_streaming Streaming Architecture
 *
 * For streaming mode (OSL_FMT_STREAM), the implementation uses a double-buffering
 * system to avoid file I/O operations inside the audio callback:
 *
 * - Two 8KB buffers are pre-filled with audio data
 * - The audio callback only reads from pre-filled memory buffers
 * - Buffers are refilled asynchronously before each decode cycle
 * - This prevents deadlocks that would occur with direct file I/O in callbacks
 *
 * @section bgm_usage Usage Example
 *
 * @code
 * // Load BGM with streaming (recommended for large files)
 * OSL_SOUND *bgm = oslLoadSoundFileBGM("music.bgm", OSL_FMT_STREAM);
 *
 * // Load BGM into RAM (faster, but uses more memory)
 * OSL_SOUND *bgm = oslLoadSoundFileBGM("music.bgm", OSL_FMT_NONE);
 *
 * // Play the sound
 * oslPlaySound(bgm, 0);  // 0 = don't loop, use voice auto-assignment
 * @endcode
 */

#ifndef _OSL_BGM_H_
#define _OSL_BGM_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @struct BGM_FORMAT_HEADER
 * @brief Header structure for BGM (Background Music) files.
 *
 * BGM files consist of this header followed by IMA-ADPCM compressed audio data.
 * The format provides 4:1 compression ratio compared to raw PCM audio.
 *
 * @note BGM files can be created using the bgm-encoder tool included with OSLib.
 * @note This structure must be packed to match the exact file format (53 bytes).
 */
#pragma pack(push, 1)
typedef struct {
	/**
	 * @brief Version string of the BGM format.
	 *
	 * This is always set to "OSLBGM v01" to indicate the version of the BGM format.
	 *
	 * @note The string is null-terminated and occupies 11 bytes.
	 */
	char strVersion[11];

	/**
	 * @brief Padding byte for alignment compatibility.
	 *
	 * This byte ensures compatibility with BGM files generated by wav2bgm tool
	 * compiled with MSVC, which adds padding after strVersion for int alignment.
	 */
	unsigned char padding;

	/**
	 * @brief Format version.
	 *
	 * Indicates the version of the BGM format. This value is always set to 1.
	 *
	 * @note The value should always be 1.
	 */
	int format;

	/**
	 * @brief Audio sampling rate.
	 *
	 * Specifies the number of samples per second (in Hz) used in the audio data.
	 */
	int sampleRate;

	/**
	 * @brief Number of audio channels.
	 *
	 * Specifies the number of audio channels:
	 * - 1 for mono
	 * - 2 for stereo
	 */
	unsigned char nbChannels;

	/**
	 * @brief Reserved space.
	 *
	 * This field is reserved for future use and should be set to zero. It is not used in
	 * the current format version.
	 *
	 * @note The reserved field occupies 32 bytes.
	 */
	unsigned char reserved[32];
} BGM_FORMAT_HEADER;
#pragma pack(pop)

#ifdef __cplusplus
}
#endif

#endif /* _OSL_BGM_H_ */
