name: Build
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [
          [macos-latest, arm64, bash],
          [macos-15-intel, x86_64, bash],
          [ubuntu-latest, x86_64, bash],
          [ubuntu-24.04-arm, arm64, bash]
        ]
      fail-fast: false
    defaults:
      run:
        shell: ${{ matrix.os[2] }} {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - &setup_pspdev
        name: Setup PSPDEV Environment
        run: |
          .github/scripts/setup_pspdev.sh "${{ matrix.os[0] }}" "${{ matrix.os[1] }}"
      - name: Runs build in shell
        run: |
          make
          make install

      - name: Build all samples
        run: |
          for d in samples/*/ ; do
            if [ -f "$d/makefile" ] || [ -f "$d/Makefile" ]; then
              echo "Building $d"
              make -C "$d"
            fi
          done
